# Write Kubernetes Deployment Script

#
# To deploy:
#
# kubectl apply -f scripts/deployment.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: week8_5:1
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://week08_fqi1_user:srYwLVOqPYBXEiUePLyXnqgsFOiYuRNd@dpg-crgoelqj1k6c739ka550-a.oregon-postgres.render.com/week08_fqi1"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000